%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-turtlebot3-automatic-parking-vision
Version:        1.3.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS turtlebot3_automatic_parking_vision package

License:        Apache 2.0
URL:            http://turtlebot3.robotis.com
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-scipy
Requires:       ros-humble-geometry-msgs
Requires:       ros-humble-nav-msgs
Requires:       ros-humble-rclpy
Requires:       ros-humble-std-msgs
Requires:       ros-humble-tf2-ros
Requires:       ros-humble-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-scipy
BuildRequires:  ros-humble-geometry-msgs
BuildRequires:  ros-humble-nav-msgs
BuildRequires:  ros-humble-rclpy
BuildRequires:  ros-humble-ros-workspace
BuildRequires:  ros-humble-std-msgs
BuildRequires:  ros-humble-tf2-ros
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Automatic Parking Vision for TurtleBot3 Examples.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/humble"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Mon Jun 23 2025 Pyo <pyo@robotis.com> - 1.3.3-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 1.3.2-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 1.3.1-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 1.3.0-3
- Autogenerated by Bloom

* Fri Jun 20 2025 Pyo <pyo@robotis.com> - 1.3.0-2
- Autogenerated by Bloom

* Wed Jun 18 2025 Pyo <pyo@robotis.com> - 1.3.0-1
- Autogenerated by Bloom

